server:
  port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/university_management_system?useSSL=false
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: update
        show-SQL: true
#JPA setting
# we can use create or update


     
